name: "spellcheck"
on:
  push:

permissions:
  contents: read

jobs:
  spellcheck:
    name:"spellcheck"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Install ispell"
        run: sudo apt install ispell

      - name: "Run spellchecker"
        run: cat Seasick-Brewing.md | ispell -p brewing.en_US -l
