name: "spellcheck"
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  spellcheck:
    name: "spell"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Install ispell"
        run: sudo apt install ispell

      - name: "Run spellchecker"
        run: cat Seasick-Brewing.md | ispell -p brewing.en_US -l | sort | uniq

  report:
    name: "report"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
      with:
        script: |
          github.rest.issues.createComment({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          body: ${{ steps.spell.outputs.stdout }}
          })
